service: portafoliopy
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:  
  create_user:
    handler: handler.create_user
    events:
      - httpApi:
          path: /create_user
          method: post
  
  login:
    handler: handler.login
    events:
      - httpApi:
          path: /login
          method: post

  recove_password:
    handler: handler.recove_password
    events:
      - httpApi:
          path: /recove_password
          method: post
  
  new_pass:
    handler: handler.new_pass
    events:
      - httpApi:
          path: /new_pass
          method: post

plugins:
  - serverless-offline